// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Pages = Collections['pages']['schema']['_output']
export declare const pages: Pages[]

export type Controls = Collections['controls']['schema']['_output']
export declare const controls: Controls[]
